name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.6"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
#    - name: ðŸ”¥ Launching pytest
#      run: |
#        python -m pytest -c .github/settings/pytest.ini
    - name: ðŸ”¥ Analysing the code with pylint
      run: |
        pylint --rcfile=.github/settings/.pylintrc $(git ls-files '*.py')
    - name: ðŸ”¥ Analysing the code with isort
      run: |
        isort -c $(git ls-files '*.py')
    - name: ðŸ”¥ Analysing the code with flake8
      run: |
        flake8 --config .github/settings/.flake8 $(git ls-files '*.py')
    - name: ðŸ”¥ Analysing the code with black
      run: |
        black --check --config .github/settings/.black $(git ls-files '*.py')
    - name: ðŸ”¥ Analysing the code with mypy
      run: |
        mypy --config-file .github/settings/mypy.ini $(git ls-files '*.py')
        
